#!/bin/sh

#default colors of the script
#BLANK='#00000000'
#CLEAR='#ffffff22'
#DEFAULT='#ff00ffcc'
#TEXT='#ee00eeee'
#WRONG='#880000bb'
#VERIFYING='#bb00bbbb'

#008f11
BLANK='#59155966'
CLEAR='#008f1166'                                                                       
DEFAULT='#380d38cc'
TEXT='#0d0208ee'
WRONG='#0d0208bb'
VERIFYING='#003b00bb'


i3lock \
--insidever-color=$CLEAR     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$WRONG         \
--bshl-color=$WRONG          \
\
--screen 1                   \
--blur 5                     \
--clock                      \
--indicator                  \
--time-str="%H:%M:%S"        \
--date-str="%A, %m %Y"       \
--keylayout 1                \
